export type AllergenModule = {
  slug: string
  name: string
  emoji: string
  colour: string   // tailwind bg class
  tagline: string
  whatIsIt: string
  hiddenIn: string[]
  symptoms: string[]
  kitchenTips: string[]
  ukLaw: string
  quiz: { q: string; options: string[]; answer: number }[]
}

export const ALLERGEN_MODULES: AllergenModule[] = [
  {
    slug: 'celery',
    name: 'Celery',
    emoji: '🥬',
    colour: 'bg-green-100',
    tagline: 'The hidden flavour booster',
    whatIsIt: 'Celery includes the stalk, leaves, seeds and root (celeriac). It is commonly used as a flavouring and can cause severe reactions even in small amounts.',
    hiddenIn: [
      'Stock cubes and bouillon',
      'Soups and stews',
      'Spice mixes and seasoning blends',
      'Crisps and snacks',
      'Celery salt (often used in Bloody Marys)',
      'Some sauces and dressings',
      'Vegetable juice',
    ],
    symptoms: [
      'Tingling or itching in the mouth',
      'Swelling of the lips, tongue or throat',
      'Hives or skin rash',
      'Runny nose and sneezing',
      'Anaphylaxis (severe cases)',
    ],
    kitchenTips: [
      'Check all stock cubes and powder seasoning labels carefully',
      'Use dedicated chopping boards — celery juice can contaminate surfaces',
      'Never use celery garnish on dishes marked allergen-free',
      'Celeriac and celery are the same allergen — declare both',
    ],
    ukLaw: 'Celery is one of the 14 major allergens regulated under UK Food Information Regulations. It must be emphasised on menus and food labels.',
    quiz: [
      { q: 'Which part of the celery plant must be declared as an allergen?', options: ['Only the stalk', 'Only the seeds', 'Stalk, leaves, seeds and root', 'Only when served raw'], answer: 2 },
      { q: 'Which of these is likely to contain hidden celery?', options: ['Plain rice', 'Stock cubes', 'Olive oil', 'Plain pasta'], answer: 1 },
      { q: 'Is celeriac (celery root) the same allergen as celery?', options: ['No, they are different allergens', 'Yes, both must be declared', 'Only celeriac needs declaring', 'Only celery needs declaring'], answer: 1 },
    ],
  },
  {
    slug: 'gluten',
    name: 'Cereals containing gluten',
    emoji: '🌾',
    colour: 'bg-amber-100',
    tagline: 'In far more than just bread',
    whatIsIt: 'Gluten is a protein found in wheat, rye, barley and oats. It is one of the most common allergens and is found in a huge range of processed foods. Coeliac disease is an autoimmune condition triggered by gluten — even trace amounts cause serious damage.',
    hiddenIn: [
      'Soy sauce (most contain wheat)',
      'Malt vinegar',
      'Battered or breaded foods',
      'Pasta, noodles and couscous',
      'Beer and ales',
      'Gravies and sauces thickened with flour',
      'Some communion wafers and medications',
      'Spice blends using wheat flour as anti-caking agent',
    ],
    symptoms: [
      'Digestive pain, bloating and diarrhoea',
      'Chronic fatigue and brain fog (coeliac)',
      'Skin rash — dermatitis herpetiformis',
      'Mouth ulcers',
      'Anaphylaxis (wheat allergy, distinct from coeliac)',
    ],
    kitchenTips: [
      'Dedicated "gluten-free" fryer oil — shared fryers cause cross-contamination',
      'Use tamari (GF soy sauce) for all gluten-free dishes',
      'Clean surfaces and utensils thoroughly — flour particles travel in air',
      'Always check pasta, breadcrumbs and flour alternatives are certified GF',
      'Oats are technically gluten-free but often contaminated — use certified GF oats',
    ],
    ukLaw: 'Wheat, rye, barley and oats must all be declared. Spelt and khorasan (Kamut) are forms of wheat and also require declaration.',
    quiz: [
      { q: 'Which grain does NOT naturally contain gluten?', options: ['Wheat', 'Rye', 'Rice', 'Barley'], answer: 2 },
      { q: 'A customer with coeliac disease orders a gluten-free dish. Why must you use a clean fryer?', options: ['For flavour reasons', 'Shared oil causes cross-contamination', 'It is not necessary', 'Only if they request it'], answer: 1 },
      { q: 'Does standard soy sauce usually contain gluten?', options: ['No, it is always gluten-free', 'Yes — most contain wheat', 'Only Japanese soy sauce', 'Only dark soy sauce'], answer: 1 },
    ],
  },
  {
    slug: 'crustaceans',
    name: 'Crustaceans',
    emoji: '🦞',
    colour: 'bg-red-100',
    tagline: 'A high-risk allergen in seafood kitchens',
    whatIsIt: 'Crustaceans include crabs, lobster, prawns, shrimp, scampi, crayfish and barnacles. Shellfish allergy is one of the most common adult-onset allergies and often causes severe reactions.',
    hiddenIn: [
      'Prawn crackers',
      'Thai fish cakes and pastes',
      'Worcestershire sauce (some brands contain anchovies and may cross-contaminate)',
      'Seafood stocks, bisques and bouillabaisse',
      'Sushi rolls and dim sum',
      'Some ready-made noodle sauces',
      'Paella and risotto',
    ],
    symptoms: [
      'Hives, itching or eczema flare-up',
      'Swelling of lips, face, tongue and throat',
      'Wheezing and shortness of breath',
      'Stomach cramps, vomiting',
      'Anaphylaxis — can be rapid and life-threatening',
    ],
    kitchenTips: [
      'Use separate tongs, boards and pans for crustaceans',
      'Never reuse water used to cook prawns or crab',
      'Clearly label all items containing prawn in mise en place',
      'Steam from cooking crustaceans can trigger reactions — ventilate and warn allergic customers',
      'Treat prawn crackers as a declared allergen dish',
    ],
    ukLaw: 'Crustaceans are one of the 14 major allergens. Molluscs (clams, mussels, oysters) are a SEPARATE allergen category.',
    quiz: [
      { q: 'Are molluscs (mussels, oysters) in the same allergen category as crustaceans?', options: ['Yes, they are the same', 'No, they are a separate allergen', 'Only if served together', 'Depends on the recipe'], answer: 1 },
      { q: 'Can steam from cooking prawns trigger a reaction in allergic customers?', options: ['No, cooking destroys the allergen', 'Yes, steam can carry proteins', 'Only if the customer is very sensitive', 'No scientific evidence exists'], answer: 1 },
      { q: 'Which of these contains hidden crustacean allergen?', options: ['Plain vegetable stock', 'Prawn crackers', 'Plain white rice', 'Olive oil'], answer: 1 },
    ],
  },
  {
    slug: 'eggs',
    name: 'Eggs',
    emoji: '🥚',
    colour: 'bg-yellow-100',
    tagline: 'More places than you think',
    whatIsIt: 'Egg allergy is very common in children, though many outgrow it. In adults, egg allergy can persist and cause severe reactions. Both egg white (albumin) and yolk can cause reactions.',
    hiddenIn: [
      'Fresh pasta and egg noodles',
      'Mayonnaise, aioli and hollandaise',
      'Brioche, waffles and pancakes',
      'Glazed pastries (egg wash)',
      'Meringue, mousse and soufflé',
      'Some breadcrumbs and coatings',
      'Caesar dressing (traditional recipe)',
      'Lecithin (E322) — usually from soy but can be from egg',
    ],
    symptoms: [
      'Skin reactions — hives, swelling, eczema',
      'Digestive issues — nausea, stomach cramps',
      'Respiratory problems — wheezing, runny nose',
      'Anaphylaxis in severe cases',
    ],
    kitchenTips: [
      'Wash hands thoroughly after handling eggs — avoid touching surfaces',
      'Use a dedicated brush for egg wash, never shared',
      'Clearly mark egg-free dishes — ensure no egg glaze or garnish is added at pass',
      'Aquafaba (chickpea water) can replace eggs in some recipes',
    ],
    ukLaw: 'Eggs from all poultry must be declared. Products containing egg must be clearly labelled.',
    quiz: [
      { q: 'Which part of the egg most commonly causes allergic reactions?', options: ['Only the yolk', 'Only the white', 'Both white and yolk can cause reactions', 'The shell'], answer: 2 },
      { q: 'Which of these typically contains egg?', options: ['Plain vegetable oil', 'Caesar dressing', 'White wine vinegar', 'Plain tomato sauce'], answer: 1 },
      { q: 'A dish is marked egg-free. What must you check before serving?', options: ['Nothing — if the recipe has no eggs it is fine', 'No egg wash, garnish or shared equipment was used', 'Only check the sauce', 'Ask the customer if they are sure about their allergy'], answer: 1 },
    ],
  },
  {
    slug: 'fish',
    name: 'Fish',
    emoji: '🐟',
    colour: 'bg-blue-100',
    tagline: 'Easily hidden in sauces and seasonings',
    whatIsIt: 'Fish allergy covers all fish species. It is distinct from shellfish allergy — someone allergic to fish may not be allergic to shellfish and vice versa. Fish proteins are stable and not destroyed by cooking or heat.',
    hiddenIn: [
      'Worcestershire sauce (contains anchovies)',
      'Caesar dressing',
      'Fish sauce and nam pla',
      'Soy sauce (some brands)',
      'Surimi (imitation crab) — made from fish',
      'Some vitamins and supplements (fish oil)',
      'Bouillabaisse and bisques',
      'Pizza toppings — anchovy paste',
    ],
    symptoms: [
      'Hives, swelling, runny nose',
      'Digestive upset — nausea, vomiting, diarrhoea',
      'Asthma and breathing difficulty',
      'Anaphylaxis — often rapid',
    ],
    kitchenTips: [
      'Fish proteins in steam and vapour can trigger reactions — keep allergic customers away from kitchen',
      'Worcestershire sauce must be declared — it contains anchovies',
      'Cross-contamination risk is high in seafood kitchens — use dedicated equipment',
      'Always check "vegetarian" Worcestershire sauce alternatives if needed',
    ],
    ukLaw: 'All fish species are covered under the fish allergen. The specific type of fish used should be declared (e.g. salmon, cod).',
    quiz: [
      { q: 'Does Worcestershire sauce typically contain fish?', options: ['No, it is always fish-free', 'Yes — it contains anchovies', 'Only some brands', 'Only if stated on the label'], answer: 1 },
      { q: 'Can cooking fish make it safe for someone with a fish allergy?', options: ['Yes, heat destroys fish proteins', 'No, fish proteins survive cooking', 'Only if cooked above 180°C', 'Only for mild allergies'], answer: 1 },
      { q: 'What is surimi?', options: ['A type of seaweed', 'Imitation crab made from fish', 'A shellfish', 'A Japanese sauce'], answer: 1 },
    ],
  },
  {
    slug: 'lupin',
    name: 'Lupin',
    emoji: '🌸',
    colour: 'bg-purple-100',
    tagline: 'The rising threat in gluten-free products',
    whatIsIt: 'Lupin (also spelled lupine) is a legume — part of the same family as peanuts. Lupin flour is increasingly used in gluten-free baking and pasta. People with peanut allergies are at higher risk of lupin allergy.',
    hiddenIn: [
      'Gluten-free flour blends',
      'Gluten-free pasta',
      'Some bread and pastry products',
      'Pancake mixes',
      'Some meat substitutes and plant-based products',
    ],
    symptoms: [
      'Hives and swelling',
      'Rhinitis and asthma',
      'Digestive symptoms',
      'Anaphylaxis — especially in those with peanut allergy',
    ],
    kitchenTips: [
      'Always check gluten-free flour ingredients — lupin is increasingly common',
      'Warn customers with peanut allergies that lupin presents cross-reactive risk',
      'Label any dish containing lupin flour clearly',
    ],
    ukLaw: 'Lupin is one of the 14 major allergens in UK law. It must be clearly emphasised on menus and labels.',
    quiz: [
      { q: 'Which allergen group are lupin seeds related to?', options: ['Tree nuts', 'Peanuts and legumes', 'Cereals', 'Molluscs'], answer: 1 },
      { q: 'Where is lupin flour most commonly found?', options: ['Meat products', 'Gluten-free baked goods', 'Dairy products', 'Seafood'], answer: 1 },
      { q: 'A customer has a peanut allergy. Should you warn them about lupin?', options: ['No, they are completely different', 'Yes, cross-reactive risk is higher', 'Only if they ask', 'Peanut allergy is unrelated to lupin'], answer: 1 },
    ],
  },
  {
    slug: 'milk',
    name: 'Milk',
    emoji: '🥛',
    colour: 'bg-sky-100',
    tagline: 'Distinct from lactose intolerance',
    whatIsIt: 'Milk allergy is an immune response to proteins in milk (casein and whey). This is different from lactose intolerance, which is a digestive issue. Milk allergy can cause anaphylaxis; lactose intolerance generally does not.',
    hiddenIn: [
      'Butter and ghee',
      'Cream, crème fraîche and yoghurt',
      'Cheese — including hard cheeses',
      'Chocolate (most contain milk solids)',
      'Some crisps and savoury snacks',
      'Processed meats (some contain milk proteins)',
      'Non-dairy creamers (some contain casein)',
      'Bread and baked goods',
    ],
    symptoms: [
      'Hives, eczema, swelling',
      'Vomiting and stomach cramps (rapid-onset)',
      'Runny nose, coughing',
      'Anaphylaxis in severe cases',
    ],
    kitchenTips: [
      'Butter, ghee and clarified butter all contain milk allergens',
      'Dark chocolate often contains milk — check labels',
      'Non-dairy doesn\'t always mean milk-free — check casein content',
      'Use plant-based alternatives (oat milk, coconut cream) for milk-free dishes',
      'Clean surfaces thoroughly — milk proteins are sticky',
    ],
    ukLaw: 'All milk and dairy products must be declared. Lactose-free milk still contains milk proteins and must be declared.',
    quiz: [
      { q: 'What is the key difference between milk allergy and lactose intolerance?', options: ['They are the same condition', 'Milk allergy is immune-based; lactose intolerance is digestive', 'Lactose intolerance is more serious', 'Milk allergy only affects children'], answer: 1 },
      { q: 'Does ghee (clarified butter) contain milk allergen?', options: ['No — the proteins are removed during clarification', 'Yes — milk proteins remain', 'Only if made from cow\'s milk', 'Only unpasteurised ghee'], answer: 1 },
      { q: 'Can lactose-free milk still cause a milk allergy reaction?', options: ['No — removing lactose makes it safe', 'Yes — milk proteins remain present', 'Only in severe cases', 'No reaction possible from lactose-free products'], answer: 1 },
    ],
  },
  {
    slug: 'molluscs',
    name: 'Molluscs',
    emoji: '🦪',
    colour: 'bg-teal-100',
    tagline: 'Separate from crustaceans — always declare both',
    whatIsIt: 'Molluscs include clams, mussels, oysters, scallops, squid (calamari), octopus and snails. Mollusc and crustacean allergies are separate — someone can be allergic to one and not the other.',
    hiddenIn: [
      'Calamari (squid)',
      'Seafood platters and mixed starters',
      'Paella and seafood rice',
      'Some Asian fish sauces (oyster sauce)',
      'Worcestershire sauce (some contain oyster)',
      'Clam chowder',
    ],
    symptoms: [
      'Itching and hives',
      'Facial swelling',
      'Vomiting and diarrhoea',
      'Anaphylaxis',
    ],
    kitchenTips: [
      'Oyster sauce must be declared separately as a mollusc allergen',
      'Calamari rings contain squid — a mollusc',
      'Use separate utensils for mollusc and non-mollusc dishes',
      'Check sauces for hidden oyster sauce in Asian-inspired dishes',
    ],
    ukLaw: 'Molluscs are a separate category from crustaceans in UK allergen law. Both must be declared independently.',
    quiz: [
      { q: 'Is calamari (squid) a mollusc or crustacean?', options: ['Crustacean', 'Mollusc', 'Neither — it is fish', 'Both'], answer: 1 },
      { q: 'A customer says they are allergic to prawns (crustaceans). Are they automatically allergic to mussels?', options: ['Yes, all shellfish are the same allergen', 'No — crustacean and mollusc are separate allergens', 'Only if both come from the sea', 'Depends on the severity'], answer: 1 },
      { q: 'Which sauce commonly contains oyster (mollusc)?', options: ['Soy sauce', 'Oyster sauce', 'Fish sauce', 'Hoisin sauce'], answer: 1 },
    ],
  },
  {
    slug: 'mustard',
    name: 'Mustard',
    emoji: '🌿',
    colour: 'bg-yellow-50',
    tagline: 'Common in sauces, dressings and spice blends',
    whatIsIt: 'Mustard covers the entire plant — seeds, leaves, powder and prepared condiment. It is a potent allergen even in tiny amounts and is found in a surprising range of products.',
    hiddenIn: [
      'Curry powders and spice blends',
      'Salad dressings and vinaigrettes',
      'Mayonnaise',
      'Barbecue and marinade sauces',
      'Some breads and cheese',
      'Pickles and chutneys',
      'Hot dogs and processed meats',
      'Prepared salads (coleslaw, potato salad)',
    ],
    symptoms: [
      'Mouth tingling and swelling',
      'Skin reactions',
      'Digestive problems',
      'Anaphylaxis',
    ],
    kitchenTips: [
      'Mustard powder in spice blends must be declared',
      'Many curry powders contain mustard seeds — check labels',
      'House dressings containing mustard must be declared on menus',
      'Mustard leaves in salads are also an allergen',
    ],
    ukLaw: 'All forms of mustard — seeds, leaves, powder, oil, prepared — must be declared as allergens.',
    quiz: [
      { q: 'Does mustard powder in a spice blend need to be declared?', options: ['No, it is only a small amount', 'Yes, any amount must be declared', 'Only if above 1%', 'Only prepared mustard needs declaring'], answer: 1 },
      { q: 'Which of these might contain hidden mustard?', options: ['Plain white rice', 'Curry powder', 'Plain olive oil', 'Plain pasta'], answer: 1 },
      { q: 'Are mustard leaves (e.g. in salads) covered by the mustard allergen declaration?', options: ['No, only seeds and condiment', 'Yes — all parts of the mustard plant', 'Only seeds and powder', 'Leaves are not an allergen'], answer: 1 },
    ],
  },
  {
    slug: 'tree-nuts',
    name: 'Tree nuts',
    emoji: '🌰',
    colour: 'bg-orange-100',
    tagline: 'A broad category — know all 8 types',
    whatIsIt: 'Tree nuts include almonds, hazelnuts, walnuts, cashews, pecans, Brazil nuts, pistachios and macadamia nuts. Peanuts are NOT tree nuts — they are a separate allergen. Each nut is technically a distinct allergen, but many people are allergic to multiple types.',
    hiddenIn: [
      'Marzipan (almonds)',
      'Pesto (pine nuts — legally a tree nut)',
      'Satay sauce (peanuts, but also may contain tree nuts)',
      'Baklava and Turkish sweets',
      'Praline and nougat',
      'Nut oils (walnut, hazelnut)',
      'Some pestos and salad dressings',
      'Chocolate, truffles and confectionery',
    ],
    symptoms: [
      'Itching and swelling — often rapid',
      'Hives',
      'Abdominal pain and vomiting',
      'Anaphylaxis — tree nuts are one of the most common causes',
    ],
    kitchenTips: [
      'Declare which specific nut is used — almonds and hazelnuts are different risks',
      'Nut oils can retain allergens — declare them',
      'Pine nuts are legally tree nuts and must be declared',
      'Cross-contamination is very high risk — dedicated tools essential',
      'Never substitute one nut for another without consulting the customer',
    ],
    ukLaw: 'Eight specific tree nuts must be declared: almonds, hazelnuts, walnuts, cashews, pecans, Brazil nuts, pistachios and macadamia/Queensland nuts.',
    quiz: [
      { q: 'Are peanuts a type of tree nut?', options: ['Yes, they are a nut', 'No, peanuts are a separate allergen (legume)', 'Only when roasted', 'Depends on how they are prepared'], answer: 1 },
      { q: 'What nut is used in traditional pesto?', options: ['Walnuts', 'Pine nuts', 'Almonds', 'Cashews'], answer: 1 },
      { q: 'How many tree nuts are specifically listed in UK allergen law?', options: ['4', '6', '8', '10'], answer: 2 },
    ],
  },
  {
    slug: 'peanuts',
    name: 'Peanuts',
    emoji: '🥜',
    colour: 'bg-yellow-100',
    tagline: 'One of the most serious allergens',
    whatIsIt: 'Peanuts are legumes, not tree nuts. Peanut allergy is one of the most common and severe food allergies, often causing anaphylaxis. Even trace amounts — from cross-contamination — can trigger life-threatening reactions.',
    hiddenIn: [
      'Satay sauces and peanut butter',
      'Some curries and stews (ground peanut thickener)',
      'African and Asian dishes',
      'Some mole sauces (Mexican)',
      'Some cereal bars and health foods',
      'Groundnut oil (highly refined is usually safe, cold-pressed is not)',
      'Some Chinese restaurant dishes',
      'Praline and some chocolates',
    ],
    symptoms: [
      'Tingling or itching in mouth — can escalate rapidly',
      'Hives, swelling',
      'Anaphylaxis — can occur within minutes',
      'Drop in blood pressure and loss of consciousness (severe anaphylaxis)',
    ],
    kitchenTips: [
      'Peanut allergy is among the most likely to cause fatal anaphylaxis — extreme care always',
      'Highly refined peanut oil is usually tolerated, but cold-pressed/gourmet peanut oils are not — always declare',
      'Never use the same utensils for peanut and peanut-free dishes',
      'Staff should know where the EpiPen is and how to use it',
      'If in doubt, remove the dish from service',
    ],
    ukLaw: 'Peanuts must always be declared. Highly refined peanut oil is exempt from declaration, but best practice is to declare it anyway for safety.',
    quiz: [
      { q: 'Are peanuts botanically related to tree nuts (almonds, cashews etc)?', options: ['Yes, all nuts are the same family', 'No — peanuts are legumes (related to peas and beans)', 'Only roasted peanuts are legumes', 'Depends on the variety'], answer: 1 },
      { q: 'What should you do if unsure whether a dish contains peanut traces?', options: ['Serve it and tell the customer to be careful', 'Remove it from service for that customer', 'Only tell the customer if they ask', 'Add a disclaimer to the menu'], answer: 1 },
      { q: 'Is highly refined peanut oil always safe for peanut allergy sufferers?', options: ['Yes, always safe', 'Usually, but it should still be declared — cold-pressed peanut oil is not safe', 'No, never safe', 'Only if heated above 180°C'], answer: 1 },
    ],
  },
  {
    slug: 'sesame',
    name: 'Sesame seeds',
    emoji: '🫙',
    colour: 'bg-stone-100',
    tagline: 'Small but serious',
    whatIsIt: 'Sesame allergy is increasing in prevalence and can be severe. Sesame seeds, oil and paste (tahini) are all allergens. Reactions can be rapid and anaphylaxis is possible.',
    hiddenIn: [
      'Tahini (sesame paste) in hummus',
      'Sesame oil in Asian cooking',
      'Burger buns and bread rolls (sesame seeds)',
      'Halva and Middle Eastern sweets',
      'Some stir-fry sauces',
      'Breadsticks and crackers',
      'Falafel (some recipes)',
      'Some dips and dressings',
    ],
    symptoms: [
      'Oral allergy syndrome — tingling and itching',
      'Hives and skin reactions',
      'Difficulty swallowing',
      'Anaphylaxis',
    ],
    kitchenTips: [
      'Remove sesame seed buns from service and offer plain alternatives',
      'Tahini in hummus and dips must be declared',
      'Sesame oil is potent — even small amounts matter',
      'Check Asian sauces and marinades for sesame oil',
    ],
    ukLaw: 'Sesame seeds are one of the 14 major allergens. Both seeds and oil must be declared.',
    quiz: [
      { q: 'Does traditional hummus contain a sesame allergen?', options: ['No, hummus is allergen-free', 'Yes — tahini is sesame paste', 'Only if sesame seeds are added on top', 'Only shop-bought hummus'], answer: 1 },
      { q: 'A customer is allergic to sesame. They order a burger. What should you check?', options: ['Nothing — burgers never contain sesame', 'Whether the bun has sesame seeds', 'Only the sauce', 'Only if they request it'], answer: 1 },
      { q: 'Does sesame oil need to be declared as an allergen?', options: ['No, cooking oils are exempt', 'Yes — sesame oil must be declared', 'Only cold-pressed sesame oil', 'Only if above 1% of the dish'], answer: 1 },
    ],
  },
  {
    slug: 'soya',
    name: 'Soybeans',
    emoji: '🫘',
    colour: 'bg-lime-100',
    tagline: 'The hidden protein in processed food',
    whatIsIt: 'Soya (soy) is a legume used extensively in processed foods as a protein, emulsifier or thickener. Highly refined soya oil and soya lecithin are usually tolerated by those with soya allergy, but best practice is to declare them.',
    hiddenIn: [
      'Tofu and tempeh',
      'Edamame beans',
      'Soy sauce and miso',
      'Many plant-based meat alternatives',
      'Baby formula',
      'Protein supplements',
      'Some margarines and spreads',
      'Lecithin (E322) in chocolate',
    ],
    symptoms: [
      'Skin reactions — hives and eczema',
      'Digestive symptoms',
      'Runny nose and watery eyes',
      'Rarely, anaphylaxis',
    ],
    kitchenTips: [
      'Check all plant-based and vegan products — soy protein is common',
      'Most dark and milk chocolate contains soy lecithin',
      'Miso soup is made from fermented soya',
      'Edamame beans are immature soybeans — declare them',
    ],
    ukLaw: 'Soybeans must be declared. Highly refined soya oil and soya lecithin are exempt, but good practice is to declare them.',
    quiz: [
      { q: 'What are edamame beans?', options: ['A type of pea', 'Immature soybeans — a soya allergen', 'A legume unrelated to soya', 'Only a soya allergen when cooked'], answer: 1 },
      { q: 'Which of these is a soya-based product?', options: ['Tahini', 'Miso paste', 'Oyster sauce', 'Fish sauce'], answer: 1 },
      { q: 'Does soya lecithin in chocolate need to be declared?', options: ['No, lecithin is always exempt', 'Technically exempt, but best practice is to declare it', 'Only if it exceeds 1%', 'Only in dark chocolate'], answer: 1 },
    ],
  },
  {
    slug: 'sulphites',
    name: 'Sulphur dioxide & sulphites',
    emoji: '🍷',
    colour: 'bg-pink-100',
    tagline: 'The preservative in wine, dried fruit and more',
    whatIsIt: 'Sulphur dioxide (SO₂) and sulphites are preservatives used widely in food and drink. They must be declared when present at more than 10mg/kg or 10mg/litre. They are commonly associated with wine and can trigger asthma.',
    hiddenIn: [
      'Wine and cider (often high levels)',
      'Dried fruits — apricots, raisins, dates',
      'Grape juice',
      'Some vinegars',
      'Pickles and pickled onions',
      'Preserved meats (sausages, burgers)',
      'Soft drinks and fruit juices',
      'Maraschino cherries',
    ],
    symptoms: [
      'Asthma and wheezing — especially common trigger',
      'Headaches (especially wine-related)',
      'Skin flushing',
      'Runny nose',
      'Rarely, anaphylaxis',
    ],
    kitchenTips: [
      'Dried apricots are very high in sulphites — common oversight in pastry kitchens',
      'House wine must have sulphite levels declared',
      'Pickled products often contain sulphites — check supplier specs',
      'Reduce-based sauces using wine carry sulphites — must be declared',
    ],
    ukLaw: 'Sulphites must be declared when levels exceed 10mg/kg or 10mg/litre. Applies to SO₂ and all sulphite salts (sodium sulphite, bisulphite etc).',
    quiz: [
      { q: 'At what level do sulphites need to be declared?', options: ['Any detectable level', 'Above 10mg/kg or 10mg/litre', 'Above 100mg/kg', 'Only in alcoholic drinks'], answer: 1 },
      { q: 'Which of these foods is typically high in sulphites?', options: ['Fresh strawberries', 'Dried apricots', 'Plain chicken breast', 'Fresh milk'], answer: 1 },
      { q: 'A guest with sulphite sensitivity orders a wine reduction sauce. What should you tell them?', options: ['Wine sauces are always safe once cooked', 'Sulphites survive cooking and must be declared', 'Only fresh wine triggers reactions', 'Reduction removes all sulphites'], answer: 1 },
    ],
  },
]

export const ALLERGEN_MODULE_MAP = Object.fromEntries(
  ALLERGEN_MODULES.map(m => [m.slug, m])
) as Record<string, AllergenModule>
